# Generated by Django 5.2.15 on 2026-06-22 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=150)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=150)),
                ('plan', models.CharField(default='starter', max_length=100)),
                ('status', models.CharField(default='inactive', max_length=100)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_customer', to='clients.clientaccount')),
            ],
        ),
    ]
