# Generated by Django 5.2.17 on 2026-09-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=150, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
