# Generated by Django 5.2.15 on 2026-06-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=80)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('industry', models.CharField(max_length=150)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(default='new', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndustryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=190, unique=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('is_supported', models.BooleanField(default=True)),
                ('summary', models.TextField(blank=True)),
                ('default_greeting', models.TextField(blank=True)),
                ('system_prompt', models.TextField(blank=True)),
                ('lead_fields', models.JSONField(blank=True, default=list)),
                ('common_questions', models.JSONField(blank=True, default=list)),
                ('escalation_rules', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
