# Generated by Django 5.2.17 on 2026-09-30 17:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_requestbudget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('profile_slug', models.SlugField(default='automotive')),
                ('published', models.BooleanField(default=False)),
                ('public_access', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemoRepAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demo_access', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DemoRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=64)),
                ('content', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='core.demoexperience')),
            ],
        ),
        migrations.AddField(
            model_name='demoexperience',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.demorevision'),
        ),
        migrations.CreateModel(
            name='DemoSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('browser_key', models.CharField(db_index=True, max_length=64)),
                ('source', models.CharField(default='public', max_length=30)),
                ('scenario', models.SlugField(default='vehicle-shopping')),
                ('state', models.JSONField(default=dict)),
                ('transcript', models.JSONField(default=list)),
                ('protocol', models.JSONField(default=list)),
                ('turns', models.PositiveIntegerField(default=0)),
                ('lease', models.UUIDField(blank=True, null=True)),
                ('busy_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experience_sessions', to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.demorevision')),
            ],
        ),
        migrations.CreateModel(
            name='DemoFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('answer', 'AI answer wrong'), ('inventory', 'Inventory mismatch'), ('voice', 'Voice problem'), ('ui', 'UI problem'), ('slow', 'Too slow'), ('scenario', 'Scenario problem'), ('question', 'Prospect question'), ('feature', 'Feature request'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(max_length=2000)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.demosession')),
            ],
        ),
        migrations.CreateModel(
            name='DemoEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, max_length=60)),
                ('metadata', models.JSONField(default=dict)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.demosession')),
            ],
        ),
        migrations.CreateModel(
            name='DemoConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vertical', models.SlugField()),
                ('scenario', models.SlugField()),
                ('source', models.CharField(max_length=30)),
                ('revision', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.consultationrequest')),
                ('rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.demosession')),
            ],
        ),
        migrations.CreateModel(
            name='DemoShareLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scenario', models.SlugField(default='vehicle-shopping')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.demoexperience')),
                ('rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='demorevision',
            constraint=models.UniqueConstraint(fields=('experience', 'version'), name='unique_demo_revision'),
        ),
    ]
