# Generated by Django 5.2.17 on 2026-09-30 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_experience_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoCRMLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default='Demo Customer', max_length=100)),
                ('stage', models.CharField(default='new', max_length=30)),
                ('assigned_to', models.CharField(default='Elena Rivera · BDC', max_length=100)),
                ('snapshot', models.JSONField(default=dict)),
                ('staff_notes', models.TextField(blank=True, max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dealership_lead', to='core.demosession')),
            ],
        ),
        migrations.CreateModel(
            name='DemoCRMActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='core.democrmlead')),
            ],
        ),
    ]
