# Generated by Django 5.2.17 on 2026-10-08 17:37

import core.booking_models
import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fictional_dealership_crm'),
        ('crm', '0017_calendlyconnection_signing_fingerprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeSchedule',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('weekdays', models.JSONField(default=core.booking_models.weekdays)),
                ('opens_at', models.TimeField(default=datetime.time(9, 0))),
                ('closes_at', models.TimeField(default=datetime.time(17, 0))),
                ('duration_minutes', models.PositiveSmallIntegerField(default=30)),
                ('buffer_minutes', models.PositiveSmallIntegerField(default=30)),
                ('notice_hours', models.PositiveSmallIntegerField(default=2)),
                ('horizon_days', models.PositiveSmallIntegerField(default=60)),
                ('notification_email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeAppointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_key', models.UUIDField(unique=True)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField()),
                ('blocked_until', models.DateTimeField()),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=80)),
                ('business_name', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=150)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('canceled', 'Canceled')], default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('owner_seen', models.BooleanField(default=False)),
                ('consultation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.consultationrequest')),
                ('lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_appointments', to='crm.lead')),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='OfficeBookingEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=30)),
                ('recipient', models.EmailField(max_length=254)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=200)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='core.officeappointment')),
            ],
        ),
        migrations.CreateModel(
            name='OfficeClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['starts_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='office_closure_positive')],
            },
        ),
        migrations.AddConstraint(
            model_name='officeappointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'confirmed')), fields=('starts_at',), name='one_office_booking_per_start'),
        ),
        migrations.AddConstraint(
            model_name='officeappointment',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='office_booking_positive'),
        ),
        migrations.AddConstraint(
            model_name='officeappointment',
            constraint=models.CheckConstraint(condition=models.Q(('blocked_until__gte', models.F('ends_at'))), name='office_booking_buffer'),
        ),
        migrations.AddConstraint(
            model_name='officebookingemail',
            constraint=models.UniqueConstraint(fields=('appointment', 'kind'), name='office_email_once_per_kind'),
        ),
    ]
