# Generated by Django 5.2.15 on 2026-06-22 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('industry', models.CharField(blank=True, max_length=150)),
                ('owner_name', models.CharField(blank=True, max_length=150)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=80)),
                ('website', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('onboarding', 'Onboarding'), ('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='onboarding', max_length=30)),
                ('plan', models.CharField(default='starter', max_length=100)),
                ('activation_status', models.CharField(choices=[('demo', 'Demo'), ('pending_payment', 'Pending Payment'), ('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='demo', max_length=40)),
                ('paid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('industry_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_accounts', to='core.industrytemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.TextField(blank=True)),
                ('services', models.TextField(blank=True)),
                ('products', models.TextField(blank=True)),
                ('faqs', models.TextField(blank=True)),
                ('service_area', models.TextField(blank=True)),
                ('policies', models.TextField(blank=True)),
                ('booking_instructions', models.TextField(blank=True)),
                ('escalation_instructions', models.TextField(blank=True)),
                ('brand_voice', models.CharField(default='friendly, helpful, professional', max_length=120)),
                ('extra_context', models.TextField(blank=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='clients.clientaccount')),
            ],
        ),
        migrations.CreateModel(
            name='AIInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('industry', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('offline', 'Offline')], default='draft', max_length=30)),
                ('greeting', models.TextField(default='Hi! How can I help today?')),
                ('system_prompt', models.TextField(blank=True)),
                ('tone', models.CharField(default='friendly, direct, helpful', max_length=150)),
                ('model', models.CharField(default='gpt-4o-mini', max_length=100)),
                ('openai_api_mode', models.CharField(choices=[('platform', 'Platform OpenAI Key'), ('client', 'Client OpenAI Key'), ('fallback', 'Fallback Only')], default='platform', max_length=30)),
                ('embed_enabled', models.BooleanField(default=True)),
                ('voice_enabled', models.BooleanField(default=False)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('collect_name', models.BooleanField(default=True)),
                ('collect_phone', models.BooleanField(default=True)),
                ('collect_email', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('industry_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_instances', to='core.industrytemplate')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_instances', to='clients.clientaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_type', models.CharField(choices=[('openai', 'OpenAI'), ('twilio', 'Twilio'), ('stripe', 'Stripe'), ('email', 'Email'), ('crm', 'CRM'), ('pos', 'POS'), ('other', 'Other')], max_length=30)),
                ('name', models.CharField(default='Default', max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('credentials', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='clients.clientaccount')),
            ],
        ),
    ]
