# Generated by Django 5.2.15 on 2026-07-04 02:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinstance',
            name='widget_primary_color',
            field=models.CharField(default='#7c3aed', help_text='Primary color for the website chat widget.', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid 6-digit hex color, like #7c3aed.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
    ]
