# Generated by Django 5.2.15 on 2026-07-14 00:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_aiinstance_widget_primary_color'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aiinstance',
            index=models.Index(fields=['client', 'status'], name='clients_aii_client__ce50cb_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinstance',
            index=models.Index(fields=['status', 'created_at'], name='clients_aii_status_64f9f6_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinstance',
            index=models.Index(fields=['industry', 'status'], name='clients_aii_industr_281b11_idx'),
        ),
        migrations.AddIndex(
            model_name='clientaccount',
            index=models.Index(fields=['user', 'created_at'], name='clients_cli_user_id_7f4c94_idx'),
        ),
        migrations.AddIndex(
            model_name='clientaccount',
            index=models.Index(fields=['activation_status', 'created_at'], name='clients_cli_activat_7d49a0_idx'),
        ),
        migrations.AddIndex(
            model_name='clientaccount',
            index=models.Index(fields=['status', 'created_at'], name='clients_cli_status_cd5abc_idx'),
        ),
    ]
