# Generated by Django 5.2.17 on 2026-10-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_ai_specialist',
            field=models.BooleanField(default=False, help_text='Qualified to document strategy and custom pricing during Growth Assessments.'),
        ),
    ]
