# Generated by Django 5.2.15 on 2026-06-22 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(blank=True, max_length=120)),
                ('customer_name', models.CharField(blank=True, max_length=150)),
                ('customer_phone', models.CharField(blank=True, max_length=80)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('summary', models.TextField(blank=True)),
                ('channel', models.CharField(default='web', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='clients.aiinstance')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('processed_status', models.CharField(default='ready', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_documents', to='clients.aiinstance')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('visitor', 'Visitor'), ('assistant', 'Assistant'), ('system', 'System'), ('staff', 'Staff')], max_length=30)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant_ai.conversation')),
            ],
        ),
    ]
