# Generated by Django 5.2.15 on 2026-07-04 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='conversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
