# Generated by Django 5.2.15 on 2026-07-13 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_assistant_roles(apps, schema_editor):
    AssistantRole = apps.get_model('assistant_ai', 'AssistantRole')
    roles = [
        ('client_assistant', 'Client-Facing Assistant', 'Tenant-isolated assistants for client demos and production widgets.'),
        ('sdr_assistant', 'SDR Assistant', 'Helps SDRs interpret leads, notes, follow-ups, and outreach drafts.'),
        ('manager_sales', 'Manager Sales Assistant', 'Helps managers inspect team sales performance and lead quality.'),
        ('growth_assessment', 'Growth Assessment Assistant', 'Supports AI growth assessment intake and meeting prep.'),
        ('internal_knowledge', 'Internal Knowledge Assistant', 'Answers authorized staff questions from approved internal knowledge.'),
    ]
    for key, name, description in roles:
        AssistantRole.objects.get_or_create(key=key, defaults={'name': name, 'description': description})


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_ai', '0002_alter_conversation_options_conversation_updated_at'),
        ('clients', '0002_aiinstance_widget_primary_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('client_assistant', 'Client-Facing Assistant'), ('sdr_assistant', 'SDR Assistant'), ('manager_sales', 'Manager Sales Assistant'), ('growth_assessment', 'Growth Assessment Assistant'), ('internal_knowledge', 'Internal Knowledge Assistant')], max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='AssistantConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('system_instructions', models.TextField()),
                ('allowed_tools', models.JSONField(blank=True, default=list)),
                ('model', models.CharField(default='gpt-4o-mini', max_length=100)),
                ('temperature', models.DecimalField(decimal_places=2, default=0.35, max_digits=3)),
                ('max_output_tokens', models.PositiveIntegerField(default=700)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='assistant_ai.assistantrole')),
            ],
            options={
                'ordering': ['role__key', '-version'],
                'unique_together': {('role', 'version')},
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistant_role', models.CharField(blank=True, max_length=80)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('fallback', 'Fallback'), ('error', 'Error'), ('blocked', 'Blocked')], default='success', max_length=30)),
                ('error_code', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.aiinstance')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.clientaccount')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['assistant_role', 'created_at'], name='assistant_a_assista_bce547_idx'), models.Index(fields=['client', 'created_at'], name='assistant_a_client__41d67a_idx'), models.Index(fields=['user', 'created_at'], name='assistant_a_user_id_03e67e_idx')],
            },
        ),
        migrations.RunPython(seed_assistant_roles, migrations.RunPython.noop),
    ]
