# Generated by Django 5.2.15 on 2026-07-14 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_ai', '0003_assistantrole_assistantconfiguration_usagerecord'),
        ('clients', '0002_aiinstance_widget_primary_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['ai_instance', 'updated_at'], name='assistant_a_ai_inst_6b4ac6_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['channel', 'updated_at'], name='assistant_a_channel_084f74_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['customer_email'], name='assistant_a_custome_6f08b6_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['ai_instance', 'processed_status'], name='assistant_a_ai_inst_103bbb_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='assistant_a_convers_623abd_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='assistant_a_sender_2239a3_idx'),
        ),
    ]
