# Generated by Django 5.2.17 on 2026-09-16 17:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_ai', '0004_alter_message_options_and_more'),
        ('core', '0002_requestbudget'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConciergeCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_digest', models.CharField(db_index=True, max_length=64)),
                ('provider_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(default='creating', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('owner_digest',), name='one_active_concierge_call')],
            },
        ),
        migrations.CreateModel(
            name='ConciergeSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.consultationrequest')),
            ],
        ),
    ]
