CORE = [
    "Welcome to AI Business Gurus & The SDR Mission",
    "AI for Business — What We’re Actually Selling",
    "AIBG Solutions — Problem → Solution Mapping",
    "Researching & Selecting Prospects",
    "Lead Finder + CRM Fundamentals",
    "Cold Calling Fundamentals & Tonality",
    "Gatekeepers & Reaching Decision-Makers",
    "Discovery & Listening",
    "Qualification & Knowing When to Walk Away",
    "Relevant AI Demonstrations",
    "Objection Handling I — Interest, Time & Existing Providers",
    "Objection Handling II — Price, Trust & AI Concerns",
    "Follow-Up That Doesn’t Suck",
    "Booking the Complimentary Growth Assessment",
    "CRM Handoff & Running a Disciplined Sales Day",
    "Core SDR Capstone + Certification",
]
ADVANCED = [
    "Running the Growth Assessment",
    "Advanced Discovery & Workflow Mapping",
    "Building the Business Case",
    "Technical Scoping & Integration Discovery",
    "Pricing, Packaging & Proposal Strategy",
    "Proposal Presentation",
    "Negotiation & Closing",
    "Client Handoff & Implementation Success",
    "Account Expansion / Upselling",
    "Advanced Sales Certification",
]
INDUSTRIES = [
    "Cannabis",
    "Insurance",
    "Med Spas",
    "Real Estate",
    "Law Firms",
    "Home Services",
    "Automotive",
]
SKILLS = {
    "company-knowledge": "Company knowledge",
    "ai-fluency": "AI fluency",
    "product-knowledge": "Product knowledge",
    "research": "Research",
    "opening": "Opening",
    "gatekeepers": "Gatekeepers",
    "tonality": "Tonality",
    "discovery": "Discovery",
    "listening": "Listening",
    "qualification": "Qualification",
    "demo": "Relevant demos",
    "business-case": "Business case",
    "objections": "Objections",
    "follow-up": "Follow-up",
    "assessment-close": "Assessment close",
    "crm-discipline": "CRM discipline",
    "industry-knowledge": "Industry knowledge",
    "ethics": "Ethics / honesty",
    "handoff": "CRM handoff",
    "accuracy": "Accuracy",
}
