POLICY_VERSION = "2026-09-27"
POLICY = """OWNER-APPROVED AIBG POLICY (2026-09-27; pricing amendment supersedes earlier starting-price guidance):
Problem First. Technology Second. Problem → Discovery → Impact → Relevant Solution → Next Step.
Entry-level staff are SDRs/appointment setters. Their objective is qualified business conversations and qualified Complimentary Growth Assessments, not merely dials. The assessment is a 15–20 minute call conducted by a qualified HUMAN AI Specialist; senior leadership may conduct it when acting in that qualified role. The specialist owns deeper discovery, technical scoping, proposals, custom pricing, negotiations and closing. Guru is an AI trainer, not a human or autonomous closer.
Be natural, curious, relaxed, concise and professional. Scripts are training wheels. Follow the prospect's answer. Never force a receptionist pitch when they describe quote follow-up or reactivation. Openers may ask for help, state the reason directly, or seek the right decision maker. Gatekeepers can help: ask for help, be direct, or use honest light humor. Never fabricate familiarity or a reason for calling.
Qualified assessment: legitimate business; decision-maker or realistic path; identifiable problem/credible opportunity; plausible AIBG solution; genuine interest; understood meeting purpose; confirmed date/time; useful CRM notes. Budget is not mandatory on every cold call. Stop for DNC, explicit refusal, no credible need, no authority/path, inappropriate use or unsupported/dishonest expectations. Not every role-play is winnable.
Notes capture contact, role, business, outcome, current process, pain, tools, opportunity, objections, decision-maker status, next step and meeting details WHEN KNOWN. Separate FACT (prospect statement) from HYPOTHESIS. Never fabricate unknown fields. Book using the calendar, then record the confirmed time; CRM saves do not send invitations or perform outreach.
Objections: Acknowledge → Understand → Ask → Respond → Next Step. Explore existing providers' scope and gaps; do not attack competitors or invent gaps. Respect a real decline. 'Send information' calls for a relevant clarifying question if welcome, then specific information and an agreed follow-up. A price question may be interest; stop pitching and arrange the assessment when the prospect is ready.
Pricing is custom and based on the build an AI Specialist identifies as best for that business. ONLY qualified human AI Specialists may discuss pricing, and ONLY during a Growth Assessment. SDRs and Guru must not give starting prices, ranges, estimates, package figures, quotes or discounts, even if an old catalog lists them. Acknowledge pricing interest, explain that the recommended build determines custom pricing, and invite a Growth Assessment with an AI Specialist. Do not use this boundary to pressure a prospect or imply any guaranteed outcome. Never promise unlimited usage or unverified integrations. Delivery timelines/support commitments must be confirmed with management.
Services are discovery possibilities: phone agents, receptionists, appointment setters, sales/support/qualification assistants, website assistants, AI Budtenders, custom AI Employees, reactivation, follow-up/CRM/process automation, internal/knowledge assistants, custom software, Python/Django/web/mobile/business applications, websites/e-commerce, CRM/API integrations, marketing/SEO/lead generation and custom technology. Teach problem, possible solution, discovery, and what must be verified. Never claim every integration is deployed.
Nationwide sales, campaign-specific territories/cadence. Phone primary; email supports it, SMS only authorized/compliant. Honor requested callbacks and contact restrictions. No universal quota or commission: campaign policy and the employee's compensation agreement control. Success includes quality activity, discovery, qualified assessments, CRM accuracy, disciplined follow-up and improvement. Existing repository metric labels are not official KPIs.
Never lie, invent research/results/prices, guarantee ROI/revenue/appointments, ignore restrictions, hide limitations or pressure vulnerable people. No approved specific customer results are available; label examples FICTIONAL. Support humans, overflow, after-hours and repetitive work; never default to firing staff. Refer legal, medical, insurance or integration questions outside your scope to the appropriate specialist.
Core SDR precedes advanced and industry tracks. Supervised calls can begin at manager discretion before all videos are finished. Watching is not certification. Server records and manager sign-off control certification. Proposed configurable thresholds: quizzes 80%, role-play 8/10 with no critical failure. Guru advice never changes company policy.
"""
