# Generated by Django 5.2.15 on 2026-07-14 02:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMessageThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=180)),
                ('is_group', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_staff_message_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffMessageParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_message_participations', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='audit.staffmessagethread')),
            ],
        ),
        migrations.CreateModel(
            name='StaffMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_staff_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='audit.staffmessagethread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeClockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('clock_in_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('clock_out_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_clock_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-clock_in'],
            },
        ),
        migrations.AddIndex(
            model_name='staffmessagethread',
            index=models.Index(fields=['updated_at'], name='audit_staff_updated_486296_idx'),
        ),
        migrations.AddIndex(
            model_name='staffmessagethread',
            index=models.Index(fields=['created_by', 'updated_at'], name='audit_staff_created_484b72_idx'),
        ),
        migrations.AddIndex(
            model_name='staffmessagethread',
            index=models.Index(fields=['is_group', 'updated_at'], name='audit_staff_is_grou_3439ef_idx'),
        ),
        migrations.AddIndex(
            model_name='staffmessageparticipant',
            index=models.Index(fields=['user', 'is_active'], name='audit_staff_user_id_0eb921_idx'),
        ),
        migrations.AddIndex(
            model_name='staffmessageparticipant',
            index=models.Index(fields=['thread', 'is_active'], name='audit_staff_thread__d5cae8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='staffmessageparticipant',
            unique_together={('thread', 'user')},
        ),
        migrations.AddIndex(
            model_name='staffmessage',
            index=models.Index(fields=['thread', 'created_at'], name='audit_staff_thread__2f4e9c_idx'),
        ),
        migrations.AddIndex(
            model_name='staffmessage',
            index=models.Index(fields=['sender', 'created_at'], name='audit_staff_sender__f832d3_idx'),
        ),
        migrations.AddIndex(
            model_name='timeclockentry',
            index=models.Index(fields=['employee', 'clock_in'], name='audit_timec_employe_a05a6a_idx'),
        ),
        migrations.AddIndex(
            model_name='timeclockentry',
            index=models.Index(fields=['employee', 'clock_out'], name='audit_timec_employe_068b9a_idx'),
        ),
        migrations.AddIndex(
            model_name='timeclockentry',
            index=models.Index(fields=['clock_out', 'clock_in'], name='audit_timec_clock_o_8e1e37_idx'),
        ),
    ]
