# Generated by Django 5.2.15 on 2026-07-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_staffmessageattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmessageparticipant',
            name='last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
