# Generated by Django 5.2.15 on 2026-07-16 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_staffmessageparticipant_last_read_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='audit.staffmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_message_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['emoji', 'created_at'],
                'indexes': [models.Index(fields=['message', 'emoji'], name='audit_staff_message_34cb1d_idx'), models.Index(fields=['user', 'created_at'], name='audit_staff_user_id_c5f3d0_idx')],
                'unique_together': {('message', 'user', 'emoji')},
            },
        ),
    ]
