# Generated by Django 5.2.17 on 2026-09-22 01:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_staffmessagereaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmessage',
            name='client_nonce',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffmessageparticipant',
            name='muted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StaffNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound', models.CharField(choices=[('aurora', 'Aurora'), ('glass', 'Glass'), ('pulse', 'Pulse'), ('soft', 'Soft chime'), ('none', 'Silent')], default='aurora', max_length=20)),
                ('volume', models.PositiveSmallIntegerField(default=40)),
                ('desktop', models.BooleanField(default=False)),
                ('previews', models.BooleanField(default=True)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffVideoCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_calls', to='audit.staffmessagethread')),
            ],
        ),
        migrations.AddField(
            model_name='staffmessage',
            name='video_call',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcement', to='audit.staffvideocall'),
        ),
        migrations.AddConstraint(
            model_name='staffmessage',
            constraint=models.UniqueConstraint(fields=('sender', 'client_nonce'), name='staff_message_sender_nonce'),
        ),
    ]
