# Generated by Django 5.2.17 on 2026-09-22 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_staffmessage_client_nonce_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmessage',
            name='video_call',
        ),
        migrations.DeleteModel(
            name='StaffVideoCall',
        ),
    ]
