# Generated by Django 5.2.17 on 2026-09-30 16:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_defer_team_video'),
        ('crm', '0014_lead_business_verification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLeadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=150)),
                ('lead_key', models.PositiveBigIntegerField()),
                ('lead_name', models.CharField(max_length=200)),
                ('request_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('kind', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], max_length=16)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('changes', models.JSONField(default=dict)),
                ('previous_status', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('counts_as_call', models.BooleanField(default=False)),
                ('assessment_booked', models.BooleanField(default=False)),
                ('assessment_completed', models.BooleanField(default=False)),
                ('proposal', models.BooleanField(default=False)),
                ('won', models.BooleanField(default=False)),
                ('lost', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.lead')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['actor', 'created_at'], name='employee_event_actor_time')],
                'constraints': [models.UniqueConstraint(fields=('request_key', 'lead_key'), name='employee_event_request_lead')],
            },
        ),
    ]
