# Generated by Django 5.2.17 on 2026-10-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0008_employee_lead_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleadevent',
            name='evidence',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='employeeleadevent',
            name='historical',
            field=models.BooleanField(default=False),
        ),
    ]
