# Generated by Django 5.2.15 on 2026-06-22 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_type', models.CharField(choices=[('internal_sales', 'Internal Sales Lead'), ('client_customer', 'Client Customer Lead')], default='internal_sales', max_length=30)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('industry', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('source', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('demo_sent', 'Demo Sent'), ('follow_up', 'Follow-Up Needed'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost'), ('client_onboarded', 'Client Onboarded')], default='new', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='clients.aiinstance')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='clients.clientaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_notes', to='crm.lead')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
