# Generated by Django 5.2.15 on 2026-07-13 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_aiinstance_widget_primary_color'),
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_status', models.CharField(blank=True, choices=[('new', 'New'), ('not_contacted', 'Not Contacted'), ('attempted', 'Attempted'), ('no_answer', 'No Answer'), ('disconnected_number', 'Disconnected Number'), ('wrong_number', 'Wrong Number'), ('voicemail_left', 'Voicemail Left'), ('gatekeeper_reached', 'Gatekeeper Reached'), ('decision_maker_unavailable', 'Decision Maker Unavailable'), ('decision_maker_reached', 'Decision Maker Reached'), ('information_requested', 'Information Requested'), ('email_requested', 'Email Requested'), ('callback_requested', 'Callback Requested'), ('follow_up', 'Follow-Up Needed'), ('warm_lead', 'Warm Lead'), ('hot_lead', 'Hot Lead'), ('appointment_scheduled', 'Appointment Scheduled'), ('appointment_completed', 'Appointment Completed'), ('proposal_requested', 'Proposal Requested'), ('proposal_sent', 'Proposal Sent'), ('corporate_referral', 'Corporate Referral'), ('existing_vendor', 'Existing Vendor'), ('already_uses_ai', 'Already Uses AI'), ('has_internal_marketing', 'Has Internal Marketing'), ('not_interested', 'Not Interested'), ('do_not_contact', 'Do Not Contact'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost'), ('duplicate', 'Duplicate'), ('duplicate_review', 'Duplicate Review'), ('permanently_closed', 'Permanently Closed'), ('contacted', 'Contacted'), ('demo_sent', 'Demo Sent'), ('client_onboarded', 'Client Onboarded')], max_length=30)),
                ('corrected_status', models.CharField(choices=[('new', 'New'), ('not_contacted', 'Not Contacted'), ('attempted', 'Attempted'), ('no_answer', 'No Answer'), ('disconnected_number', 'Disconnected Number'), ('wrong_number', 'Wrong Number'), ('voicemail_left', 'Voicemail Left'), ('gatekeeper_reached', 'Gatekeeper Reached'), ('decision_maker_unavailable', 'Decision Maker Unavailable'), ('decision_maker_reached', 'Decision Maker Reached'), ('information_requested', 'Information Requested'), ('email_requested', 'Email Requested'), ('callback_requested', 'Callback Requested'), ('follow_up', 'Follow-Up Needed'), ('warm_lead', 'Warm Lead'), ('hot_lead', 'Hot Lead'), ('appointment_scheduled', 'Appointment Scheduled'), ('appointment_completed', 'Appointment Completed'), ('proposal_requested', 'Proposal Requested'), ('proposal_sent', 'Proposal Sent'), ('corporate_referral', 'Corporate Referral'), ('existing_vendor', 'Existing Vendor'), ('already_uses_ai', 'Already Uses AI'), ('has_internal_marketing', 'Has Internal Marketing'), ('not_interested', 'Not Interested'), ('do_not_contact', 'Do Not Contact'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost'), ('duplicate', 'Duplicate'), ('duplicate_review', 'Duplicate Review'), ('permanently_closed', 'Permanently Closed'), ('contacted', 'Contacted'), ('demo_sent', 'Demo Sent'), ('client_onboarded', 'Client Onboarded')], max_length=30)),
                ('original_temperature', models.CharField(blank=True, choices=[('cold', 'Cold'), ('warm', 'Warm'), ('hot', 'Hot'), ('closed', 'Closed')], max_length=20)),
                ('corrected_temperature', models.CharField(choices=[('cold', 'Cold'), ('warm', 'Warm'), ('hot', 'Hot'), ('closed', 'Closed')], max_length=20)),
                ('original_cleaned_note', models.TextField(blank=True)),
                ('corrected_cleaned_note', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_note', models.TextField(blank=True)),
                ('cleaned_note', models.TextField(blank=True)),
                ('inferred_status', models.CharField(choices=[('new', 'New'), ('not_contacted', 'Not Contacted'), ('attempted', 'Attempted'), ('no_answer', 'No Answer'), ('disconnected_number', 'Disconnected Number'), ('wrong_number', 'Wrong Number'), ('voicemail_left', 'Voicemail Left'), ('gatekeeper_reached', 'Gatekeeper Reached'), ('decision_maker_unavailable', 'Decision Maker Unavailable'), ('decision_maker_reached', 'Decision Maker Reached'), ('information_requested', 'Information Requested'), ('email_requested', 'Email Requested'), ('callback_requested', 'Callback Requested'), ('follow_up', 'Follow-Up Needed'), ('warm_lead', 'Warm Lead'), ('hot_lead', 'Hot Lead'), ('appointment_scheduled', 'Appointment Scheduled'), ('appointment_completed', 'Appointment Completed'), ('proposal_requested', 'Proposal Requested'), ('proposal_sent', 'Proposal Sent'), ('corporate_referral', 'Corporate Referral'), ('existing_vendor', 'Existing Vendor'), ('already_uses_ai', 'Already Uses AI'), ('has_internal_marketing', 'Has Internal Marketing'), ('not_interested', 'Not Interested'), ('do_not_contact', 'Do Not Contact'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost'), ('duplicate', 'Duplicate'), ('duplicate_review', 'Duplicate Review'), ('permanently_closed', 'Permanently Closed'), ('contacted', 'Contacted'), ('demo_sent', 'Demo Sent'), ('client_onboarded', 'Client Onboarded')], default='new', max_length=30)),
                ('lead_temperature', models.CharField(choices=[('cold', 'Cold'), ('warm', 'Warm'), ('hot', 'Hot'), ('closed', 'Closed')], default='cold', max_length=20)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('contact_role', models.CharField(blank=True, max_length=120)),
                ('activity_type', models.CharField(choices=[('imported_note', 'Imported Note'), ('call', 'Call'), ('email', 'Email'), ('sms', 'SMS'), ('follow_up', 'Follow-Up'), ('status_change', 'Status Change'), ('manual_note', 'Manual Note')], default='imported_note', max_length=30)),
                ('call_outcome', models.CharField(blank=True, max_length=120)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('classification_source', models.CharField(choices=[('manual', 'Manual'), ('rule', 'Rules Engine'), ('ai', 'AI Assisted'), ('import', 'Imported')], default='rule', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manually_reviewed', models.BooleanField(default=False)),
                ('original_row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='crm/imports/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(default='csv', max_length=20)),
                ('sheet_names', models.JSONField(blank=True, default=list)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('notes_analyzed_count', models.PositiveIntegerField(default=0)),
                ('high_confidence_count', models.PositiveIntegerField(default=0)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processed', 'Processed'), ('needs_review', 'Needs Review'), ('failed', 'Failed')], default='uploaded', max_length=30)),
                ('import_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='appointment_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='lead',
            name='classification_confidence',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='lead',
            name='classification_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('rule', 'Rules Engine'), ('ai', 'AI Assisted'), ('import', 'Imported')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='cleaned_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='contact_role',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='lead',
            name='duplicate_key',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_contact_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_temperature',
            field=models.CharField(choices=[('cold', 'Cold'), ('warm', 'Warm'), ('hot', 'Hot'), ('closed', 'Closed')], default='cold', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='next_follow_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='point_of_contact',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='lead',
            name='source_file',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='source_sheet',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='lead',
            name='state',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='lead',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('not_contacted', 'Not Contacted'), ('attempted', 'Attempted'), ('no_answer', 'No Answer'), ('disconnected_number', 'Disconnected Number'), ('wrong_number', 'Wrong Number'), ('voicemail_left', 'Voicemail Left'), ('gatekeeper_reached', 'Gatekeeper Reached'), ('decision_maker_unavailable', 'Decision Maker Unavailable'), ('decision_maker_reached', 'Decision Maker Reached'), ('information_requested', 'Information Requested'), ('email_requested', 'Email Requested'), ('callback_requested', 'Callback Requested'), ('follow_up', 'Follow-Up Needed'), ('warm_lead', 'Warm Lead'), ('hot_lead', 'Hot Lead'), ('appointment_scheduled', 'Appointment Scheduled'), ('appointment_completed', 'Appointment Completed'), ('proposal_requested', 'Proposal Requested'), ('proposal_sent', 'Proposal Sent'), ('corporate_referral', 'Corporate Referral'), ('existing_vendor', 'Existing Vendor'), ('already_uses_ai', 'Already Uses AI'), ('has_internal_marketing', 'Has Internal Marketing'), ('not_interested', 'Not Interested'), ('do_not_contact', 'Do Not Contact'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost'), ('duplicate', 'Duplicate'), ('duplicate_review', 'Duplicate Review'), ('permanently_closed', 'Permanently Closed'), ('contacted', 'Contacted'), ('demo_sent', 'Demo Sent'), ('client_onboarded', 'Client Onboarded')], default='new', max_length=30),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['lead_type', 'status'], name='crm_lead_lead_ty_9c5ba1_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['lead_type', 'lead_temperature'], name='crm_lead_lead_ty_ff277b_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to', 'follow_up_date'], name='crm_lead_assigne_cfe8c4_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['needs_review', 'created_at'], name='crm_lead_needs_r_2794e2_idx'),
        ),
        migrations.AddField(
            model_name='classificationcorrection',
            name='corrected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classificationcorrection',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_corrections', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='corrected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrected_lead_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classificationcorrection',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='crm.leadactivity'),
        ),
        migrations.AddField(
            model_name='leadimport',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='original_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='crm.leadimport'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['inferred_status', 'lead_temperature'], name='crm_leadact_inferre_d92db2_idx'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['classification_source', 'created_at'], name='crm_leadact_classif_91de97_idx'),
        ),
    ]
