# Generated by Django 5.2.15 on 2026-07-14 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_classificationcorrection_leadactivity_leadimport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadimport',
            name='updated_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
