# Generated by Django 5.2.15 on 2026-07-14 00:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_aiinstance_clients_aii_client__ce50cb_idx_and_more'),
        ('crm', '0003_leadimport_updated_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['lead_type', 'archived', 'created_at'], name='crm_lead_lead_ty_5f333f_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['lead_type', 'assigned_to', 'created_at'], name='crm_lead_lead_ty_a0408d_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['lead_type', 'source_file'], name='crm_lead_lead_ty_a1dae6_idx'),
        ),
        migrations.AddIndex(
            model_name='leadimport',
            index=models.Index(fields=['status', 'created_at'], name='crm_leadimp_status_9ccd50_idx'),
        ),
        migrations.AddIndex(
            model_name='leadimport',
            index=models.Index(fields=['uploaded_by', 'created_at'], name='crm_leadimp_uploade_900b77_idx'),
        ),
    ]
