# Generated by Django 5.2.15 on 2026-07-14 00:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_aiinstance_clients_aii_client__ce50cb_idx_and_more'),
        ('crm', '0004_lead_crm_lead_lead_ty_5f333f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['client', 'lead_type', 'created_at'], name='crm_lead_client__cbf319_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['ai_instance', 'created_at'], name='crm_lead_ai_inst_d1dff8_idx'),
        ),
    ]
