# Generated by Django 5.2.15 on 2026-07-15 21:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_aiinstance_clients_aii_client__ce50cb_idx_and_more'),
        ('crm', '0005_lead_crm_lead_client__cbf319_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['lead_type', 'source_file', 'source_sheet', 'archived'], name='crm_lead_lead_ty_471312_idx'),
        ),
    ]
