# Generated by Django 5.2.15 on 2026-07-30 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_aiinstance_clients_aii_client__ce50cb_idx_and_more'),
        ('crm', '0006_lead_crm_lead_lead_ty_471312_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadStaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=80)),
                ('industry', models.CharField(max_length=150)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('new', 'New'), ('skipped', 'Skipped')], default='new', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadGenerationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('quantity_requested', models.PositiveIntegerField(default=0)),
                ('quantity_generated', models.PositiveIntegerField(default=0)),
                ('duplicates_removed', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('generating', 'Generating'), ('searching', 'Searching'), ('deduplicating', 'Deduplicating'), ('saving', 'Saving'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=30)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('status_message', models.CharField(blank=True, max_length=255)),
                ('provider_summary', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_generation_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_generation_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_leads', to='crm.leadgenerationbatch'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['lead_type', 'lead_generation_batch'], name='crm_lead_lead_ty_729a61_idx'),
        ),
        migrations.AddField(
            model_name='leadstaging',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staged_leads', to='crm.leadgenerationbatch'),
        ),
        migrations.AddField(
            model_name='leadstaging',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_staging_rows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='leadgenerationbatch',
            index=models.Index(fields=['employee', 'created_at'], name='crm_leadgen_employe_8364bd_idx'),
        ),
        migrations.AddIndex(
            model_name='leadgenerationbatch',
            index=models.Index(fields=['status', 'created_at'], name='crm_leadgen_status_7e2061_idx'),
        ),
        migrations.AddIndex(
            model_name='leadgenerationbatch',
            index=models.Index(fields=['industry', 'created_at'], name='crm_leadgen_industr_21b8fa_idx'),
        ),
        migrations.AddIndex(
            model_name='leadstaging',
            index=models.Index(fields=['created_by', 'status', 'created_at'], name='crm_leadsta_created_c32324_idx'),
        ),
        migrations.AddIndex(
            model_name='leadstaging',
            index=models.Index(fields=['batch', 'status'], name='crm_leadsta_batch_i_a6da2a_idx'),
        ),
        migrations.AddIndex(
            model_name='leadstaging',
            index=models.Index(fields=['industry', 'created_at'], name='crm_leadsta_industr_ace3de_idx'),
        ),
        migrations.AddIndex(
            model_name='leadstaging',
            index=models.Index(fields=['city', 'state'], name='crm_leadsta_city_7cde5d_idx'),
        ),
        migrations.AddIndex(
            model_name='leadstaging',
            index=models.Index(fields=['phone_number'], name='crm_leadsta_phone_n_328299_idx'),
        ),
    ]
