# Generated by Django 5.2.17 on 2026-09-09 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_ai', '0004_alter_message_options_and_more'),
        ('crm', '0007_leadstaging_leadgenerationbatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='conversation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_lead', to='assistant_ai.conversation'),
        ),
    ]
