# Generated by Django 5.2.17 on 2026-09-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_lead_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='assessment_brief',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='leadstaging',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='leadstaging',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='leadstaging',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
