# Generated by Django 5.2.17 on 2026-09-22 01:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_lead_assessment_brief_leadstaging_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled lead sheet', max_length=150)),
                ('kind', models.CharField(choices=[('leads', 'Pipeline leads'), ('prospects', 'Finder prospects')], default='leads', max_length=20)),
                ('rows', models.JSONField(default=list)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('last_mutation_id', models.UUIDField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_sheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
