# Generated by Django 5.2.17 on 2026-09-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_leadsheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadstaging',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='leadstaging',
            name='phone_number',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
