# Generated by Django 5.2.17 on 2026-09-29 20:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_lead_business_verification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesSMSContact',
            fields=[
                ('phone', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('opted_out', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesSMSReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.CharField(max_length=120, unique=True)),
                ('phone', models.CharField(max_length=16)),
                ('body', models.TextField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutreachMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'Text')], max_length=10)),
                ('recipient', models.CharField(max_length=254)),
                ('sender', models.CharField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=180)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Submitted'), ('failed', 'Not sent'), ('unknown', 'Check delivery')], default='draft', max_length=12)),
                ('provider_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('delivery_status', models.CharField(blank=True, max_length=30)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('sms_consent_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('activity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.leadactivity')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_messages', to='crm.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffMailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('google_subject', models.CharField(max_length=255, unique=True)),
                ('refresh_token', models.TextField(editable=False)),
                ('scopes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_mailbox', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
