# Generated by Django 5.2.17 on 2026-09-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_leadstaging_email_alter_leadstaging_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='website_review',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='leadstaging',
            name='website_review',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
