# Generated by Django 5.2.17 on 2026-10-02 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_defaults(apps, schema_editor):
    Config=apps.get_model('crm','SalesEmailConfig')
    Type=apps.get_model('crm','SalesEmailType')
    Service=apps.get_model('crm','SalesEmailService')
    Config.objects.get_or_create(pk=1,defaults={'company_description': 'AI Business Gurus builds AI, automation, custom software and technology solutions around how a business actually operates. Start with the business problem, support its team, and identify an appropriate solution.', 'assessment_description': 'A complimentary 15–20 minute video Growth Assessment with an AI Specialist to understand current operations, identify bottlenecks and evaluate relevant AI/software opportunities and an implementation approach.', 'forbidden_claims': 'guaranteed ROI\nguaranteed revenue\nguaranteed savings\nseamlessly integrates'})
    for i,(slug,name,guidance,length) in enumerate([('cold', 'Cold email', 'No prior conversation or request for information may be implied. Introduce yourself, establish relevance without claiming an unobserved problem, and earn a conversation.', 'short'), ('decision_maker', 'Decision maker — requested information', 'A conversation with the decision maker occurred. Prioritize recent call notes and the specific request. Briefly acknowledge that conversation; do not turn this into a brochure.', 'standard'), ('gatekeeper', 'Gatekeeper — requested information', 'Spoke with a gatekeeper, NOT necessarily this recipient. Make it easy to forward. Use only known names. Never imply the decision maker spoke with us or the gatekeeper endorsed AIBG.', 'short'), ('follow_up', 'Follow-up', 'Review previous SENT emails and activities, find a useful reason to reconnect and move to a specific next step. Drafts are not sent messages. Avoid an empty just-checking-in email.', 'short')]):
        Type.objects.get_or_create(slug=slug,defaults={'name':name,'guidance':guidance,'default_length':length,'position':i})
    for i,(slug,name,description) in enumerate([('outbound', 'Outbound cold calling AI', 'Outbound calling, qualification, database outreach, follow-up, appointments and reactivation where appropriate. Do not promise unrestricted automated cold calling or legal compliance.'), ('receptionist', 'Receptionist / intake phone AI', 'Answer calls, after-hours and overflow coverage, FAQs, intake, qualification, routing, appointments and human escalation. Support employees rather than replace them.'), ('lead_response', 'Lead response & follow-up AI', 'Respond to leads, qualify, nurture, organize CRM follow-up and support longer-term conversations.'), ('appointments', 'Appointment setting AI', 'Qualification, availability, scheduling, rescheduling, confirmations, reminders and handoff. Calendar integrations require verification.'), ('customer_service', 'Customer service AI', 'Common questions, order or service information, routing, basic troubleshooting, status requests and human escalation.'), ('reactivation', 'Customer reactivation AI', 'Re-engage older unsold leads, past customers, inactive databases and renewal opportunities. Never guarantee conversions.'), ('operations', 'Operations automation AI', 'Repetitive administration, data movement, internal workflows, notifications, documents, task routing and employee support.'), ('crm', 'CRM automation & integration', 'Lead routing, follow-up, activity logging, data synchronization, pipeline reporting and customer lifecycle workflows. Compatibility depends on verified system/API access.'), ('website_ai', 'Website AI / customer concierge', 'Website conversations, service and product questions, qualification, recommendations, appointment assistance, support and routing.'), ('knowledge', 'Internal AI employee / knowledge assistant', 'Employee questions, approved company knowledge, procedures, internal search, training and operational assistance.'), ('budtender', 'AI Budtender', 'Cannabis product discovery, menu navigation, product education, FAQs, availability, preferences and ordering assistance across phone, website or kiosk. No medical claims or unverified commerce integrations.'), ('automotive', 'Automotive AI / BDC automation', 'Internet leads, inventory questions, vehicle discovery, qualification, test drives, trade intake, after-hours, service scheduling, reactivation and BDC handoff. No unverified CRM or DMS compatibility claims.'), ('software', 'Custom software development', 'Custom business applications, internal systems, workflow software, client portals, management systems and specialized tools.'), ('apps', 'Web / mobile applications', 'Customer-facing or internal applications, mobile applications, SaaS, portals and dashboards.'), ('websites', 'Website development', 'Custom business websites, conversion-focused experiences, e-commerce and integrated customer experiences. Avoid generic marketing claims.'), ('business_software', 'Business management software', 'Internal operations, employee and customer management, workflow management, reporting and appropriate financial/admin workflows.'), ('custom_ai', 'Custom AI solution', 'Custom AI and software systems designed around business workflows when the opportunity does not fit another category.')]):
        Service.objects.get_or_create(slug=slug,defaults={'name':name,'description':description,'position':i})


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_salessmscontact_salessmsreply_outreachmessage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesEmailConfig',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('company_description', models.TextField(max_length=2000)),
                ('assessment_description', models.TextField(max_length=1000)),
                ('forbidden_claims', models.TextField(blank=True, help_text='Additional forbidden phrases, one per line. Core restrictions always apply.', max_length=3000)),
                ('default_tone', models.CharField(choices=[('natural', 'Natural & professional'), ('direct', 'Direct'), ('consultative', 'Consultative'), ('friendly', 'Friendly'), ('executive', 'Executive')], default='natural', max_length=20)),
                ('default_length', models.CharField(blank=True, choices=[('', 'Use email type default'), ('short', 'Short'), ('standard', 'Standard'), ('detailed', 'Detailed')], max_length=20)),
                ('include_demo', models.BooleanField(default=True)),
                ('include_assessment', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesEmailService',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1500)),
                ('enabled', models.BooleanField(default=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='SalesEmailType',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('guidance', models.TextField(max_length=1500)),
                ('default_length', models.CharField(choices=[('short', 'Short'), ('standard', 'Standard'), ('detailed', 'Detailed')], default='short', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'slug'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='notes_sensitive',
            field=models.BooleanField(default=False, help_text='Exclude the main notes from AI email context.'),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='is_sensitive',
            field=models.BooleanField(default=False, help_text='Exclude from AI email context.'),
        ),
        migrations.AddField(
            model_name='leadnote',
            name='is_sensitive',
            field=models.BooleanField(default=False, help_text='Exclude from AI email context.'),
        ),
        migrations.AddField(
            model_name='outreachmessage',
            name='feedback',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='outreachmessage',
            name='feedback_reason',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='outreachmessage',
            name='generation_options',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='outreachmessage',
            name='generator_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='outreachmessage',
            name='generator_version',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AddField(
            model_name='outreachmessage',
            name='original_output',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='outreachmessage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.outreachmessage'),
        ),
        migrations.AddField(
            model_name='outreachmessage',
            name='revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outreachmessage',
            name='saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outreachmessage',
            name='signature',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='outreachmessage',
            name='subjects',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='outreachmessage',
            name='validation_result',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='outreachmessage',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Submitted'), ('failed', 'Not sent'), ('unknown', 'Check delivery'), ('marked_sent', 'Manually marked sent'), ('discarded', 'Discarded')], default='draft', max_length=12),
        ),
        migrations.CreateModel(
            name='SalesProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=150)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('business_email', models.EmailField(blank=True, max_length=254)),
                ('business_phone', models.CharField(blank=True, max_length=80)),
                ('approved_bio', models.TextField(blank=True, help_text='Approved professional credibility only. No private employee information.', max_length=1200)),
                ('scheduling_url', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(seed_defaults, migrations.RunPython.noop),
    ]
