# Generated by Django 5.2.17 on 2026-09-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_lead_website_review_leadstaging_website_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='business_verification',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='leadstaging',
            name='business_verification',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
