# Generated by Django 5.2.17 on 2026-10-06 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_lead_search_checkpoints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendlyConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_uri', models.URLField(blank=True)),
                ('user_uri', models.URLField(blank=True)),
                ('organization_uri', models.URLField(blank=True)),
                ('event_type_uri', models.URLField(blank=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_received_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee_uri', models.URLField(max_length=500, unique=True)),
                ('event_uri', models.URLField(max_length=500)),
                ('old_invitee_uri', models.URLField(blank=True, max_length=500)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('starts_at', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('provider_updated_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now=True)),
                ('meeting_url', models.URLField(blank=True, max_length=1000)),
                ('review_reason', models.CharField(blank=True, max_length=250)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('credited_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_bookings', to='crm.lead')),
            ],
        ),
        migrations.CreateModel(
            name='SalesFollowUpPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=30)),
                ('step', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('next_due', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_plan', to='crm.lead')),
            ],
        ),
        migrations.CreateModel(
            name='SalesWorkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.UUIDField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.lead')),
            ],
        ),
    ]
