# Generated by Django 5.2.17 on 2026-10-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_calendlyconnection_assessmentbooking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendlyconnection',
            name='signing_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
