# Generated by Django 5.2.15 on 2026-06-22 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_number', models.CharField(blank=True, max_length=80)),
                ('to_number', models.CharField(blank=True, max_length=80)),
                ('call_sid', models.CharField(blank=True, max_length=120)),
                ('transcript', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('status', models.CharField(default='received', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='clients.aiinstance')),
            ],
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_number', models.CharField(blank=True, max_length=80)),
                ('to_number', models.CharField(blank=True, max_length=80)),
                ('body', models.TextField(blank=True)),
                ('response', models.TextField(blank=True)),
                ('message_sid', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='clients.aiinstance')),
            ],
        ),
    ]
