# Generated by Django 5.2.17 on 2026-09-09 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_ai', '0004_alter_message_options_and_more'),
        ('voice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookReceipt',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='calllog',
            name='conversation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_log', to='assistant_ai.conversation'),
        ),
    ]
