# Generated by Django 5.2.17 on 2026-09-25 19:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(unique=True)),
                ("position", models.PositiveSmallIntegerField()),
                ("required", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["track_id", "position"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="CertificationAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("training", "Training"),
                            ("shadowing", "Shadowing"),
                            ("supervised", "Supervised calling"),
                            ("independent", "Certified / independent"),
                        ],
                        default="training",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="training_enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ManagerReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("roleplay", "Role-play review"),
                            ("practical", "Practical evaluation"),
                            ("certify", "Certification approval"),
                            ("revoke", "Certification revoked"),
                        ],
                        max_length=30,
                    ),
                ),
                ("passed", models.BooleanField(default=False)),
                ("crm_practical", models.BooleanField(default=False)),
                ("note", models.TextField()),
                ("evidence", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="training.certificationattempt",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requirements_snapshot", models.JSONField()),
                ("awarded_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certifications",
                        to="training.certificationattempt",
                    ),
                ),
                (
                    "review",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="training.managerreview",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModuleVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(default=1)),
                (
                    "policy_version",
                    models.CharField(default="2026-09-25", max_length=50),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("owner_review", "Owner review"),
                            ("approved", "Approved"),
                            ("published", "Published"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                ("transcript", models.TextField(blank=True)),
                ("scenes", models.JSONField(blank=True, default=list)),
                ("job_aid", models.TextField(blank=True)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        default=900,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="training.module",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LessonAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("captions", "Captions"),
                            ("poster", "Poster"),
                        ],
                        max_length=20,
                    ),
                ),
                ("storage_key", models.CharField(max_length=500)),
                ("reviewed", models.BooleanField(default=False)),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="training.moduleversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cycle", models.PositiveIntegerField(default=1)),
                ("watched_ranges", models.JSONField(default=list)),
                ("position_seconds", models.FloatField(default=0)),
                ("active_seconds", models.FloatField(default=0)),
                ("last_ping", models.DateTimeField(blank=True, null=True)),
                ("watch_session", models.UUIDField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="training.moduleversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProctorSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("mode", models.CharField(default="coach", max_length=20)),
                ("messages", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="training.moduleversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Apply what you learned", max_length=180),
                ),
                (
                    "version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quiz",
                        to="training.moduleversion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nonce", models.UUIDField()),
                ("answers", models.JSONField()),
                ("feedback", models.JSONField()),
                ("score", models.FloatField()),
                ("pass_percent", models.PositiveSmallIntegerField()),
                ("passed", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="training.quiz"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RolePlayAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("transcript", models.JSONField(default=list)),
                ("handoff", models.TextField(blank=True)),
                ("feedback", models.JSONField(default=dict)),
                (
                    "score",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("critical_failures", models.JSONField(default=list)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("review", "Manager review"),
                            ("reviewed", "Reviewed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("busy", models.BooleanField(default=False)),
                ("processing_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "previous",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="training.roleplayattempt",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="managerreview",
            name="roleplay",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="training.roleplayattempt",
            ),
        ),
        migrations.CreateModel(
            name="RolePlayScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("persona", models.TextField()),
                ("opening", models.TextField()),
                ("rubric", models.JSONField(default=dict)),
                (
                    "difficulty",
                    models.PositiveSmallIntegerField(
                        default=2,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                ("required", models.BooleanField(default=True)),
                ("capstone", models.BooleanField(default=False)),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scenarios",
                        to="training.moduleversion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="roleplayattempt",
            name="scenario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="training.roleplayscenario",
            ),
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField()),
                ("choices", models.JSONField(default=list)),
                ("correct_index", models.PositiveSmallIntegerField()),
                ("explanation", models.TextField()),
                ("position", models.PositiveSmallIntegerField(default=1)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questions",
                        to="training.quiz",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="training.skill",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "pk"],
            },
        ),
        migrations.AddField(
            model_name="module",
            name="skills",
            field=models.ManyToManyField(blank=True, to="training.skill"),
        ),
        migrations.CreateModel(
            name="EmployeeSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                ("evidence", models.TextField()),
                ("source", models.CharField(default="guru_advisory", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="training.roleplayattempt",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="training.skill"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("slug", models.SlugField(unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("core", "Core SDR"),
                            ("advanced", "Advanced sales"),
                            ("industry", "Industry specialization"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "quiz_pass_percent",
                    models.PositiveSmallIntegerField(
                        default=80,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "roleplay_pass_score",
                    models.PositiveSmallIntegerField(
                        default=8,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "watch_percent",
                    models.PositiveSmallIntegerField(
                        default=90,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("thresholds_proposed", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tracks",
                        to="training.course",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="module",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="modules",
                to="training.track",
            ),
        ),
        migrations.AddField(
            model_name="certificationattempt",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="training.track"
            ),
        ),
        migrations.CreateModel(
            name="TrainingAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("due_at", models.DateField(blank=True, null=True)),
                ("retraining", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="training.certificationattempt",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="training.moduleversion",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="moduleversion",
            constraint=models.UniqueConstraint(
                fields=("module", "number"), name="training_module_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonasset",
            constraint=models.UniqueConstraint(
                fields=("version", "kind"), name="training_asset_kind"
            ),
        ),
        migrations.AddConstraint(
            model_name="employeeprogress",
            constraint=models.UniqueConstraint(
                fields=("employee", "version", "cycle"), name="training_progress"
            ),
        ),
        migrations.AddConstraint(
            model_name="quizattempt",
            constraint=models.UniqueConstraint(
                fields=("employee", "nonce"), name="training_quiz_nonce"
            ),
        ),
        migrations.AddConstraint(
            model_name="certificationattempt",
            constraint=models.UniqueConstraint(
                fields=("employee", "track"), name="training_enrollment"
            ),
        ),
    ]
