# Generated by Django 5.2.17 on 2026-09-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="roleplayattempt",
            name="advisory_feedback",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
